version: '3'

services:

  starfleet_mysql:
    image: mysql:5.7
    container_name: starfleet_mysql
    ports:
      - 3333:3306
    logging:
      driver: "none"
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=true
      - MYSQL_DATABASE=startrek
      - MYSQL_USER=commander
      - MYSQL_PASSWORD=123456

  starfleet_example:
    image: dkfbasel/hot-reload-go:1.10.2
    dns_search: .
    container_name: starfleet_example
    dns_search: .
    volumes:
      - .:/go/src/github.com/dkfbasel/protobuf/example
      - ../types:/go/src/github.com/dkfbasel/protobuf/types
    environment:
      - PROJECT=github.com/dkfbasel/protobuf/example
      - CMD=build
