version: '3'

services:
  starfleet_mysql:
    image: mysql:5.7
    container_name: starfleet_mysql
    # mapping external:internal ports
    ports:
      - 3333:3306
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=true
      - MYSQL_DATABASE=startrek
      - MYSQL_USER=commander
      - MYSQL_PASSWORD=123456
