// Code generated by protoc-gen-gotags. DO NOT EDIT.
// source: grpcservice.proto

/*
Package grpcservice is a generated protocol buffer package.

It is generated from these files:
	grpcservice.proto

It has these top-level messages:
	WrinkledItem
	SmoothItem
	Item
*/
package grpcservice

import protodef "github.com/dkfbasel/protobuf/example/domain/proto"
import fmt "fmt"
import dkfbasel_protobuf "github.com/dkfbasel/protobuf/types/timestamp"
import dkfbasel_protobuf1 "github.com/dkfbasel/protobuf/types/nullstring"

// Reference imports to suppress errors if they are not otherwise used.
var _ = fmt.Errorf

// WrinkledItem is used for items with multiple wrinkes
type WrinkledItemAlias struct {
	// customer will contain the name of the customer
	Customer string
	// nested messages can be embedded directly using the tag compose:"embed"
	Item               *Item                        `compose:"embed"`
	BroughtIn          *dkfbasel_protobuf.Timestamp `db:"brought_in_for_something"`
	ThisCouldBeNothing *dkfbasel_protobuf1.NullString
}

// SmoothItem is used as response with associated costs
type SmoothItemAlias struct {
	Item *Item `compose:"embed"`
	Cost int32 // cost in USD
}

// Item contains the information about a specific item
type ItemAlias struct {
	Name     string `db:"name" json:"name,omitempty"`
	Wrinkels int32  `db:"no_wrinkles" json:"wrinkels,omitempty"`
}
