// Code generated by protoc-gen-gotags. DO NOT EDIT.
// source: grpcservice.proto

/*
Package grpcservice is a generated protocol buffer package.

It is generated from these files:
	grpcservice.proto

It has these top-level messages:
	WrinkledItem
	SmoothItem
	Item
*/
package grpcservice

import protodef "github.com/dkfbasel/protobuf/example/domain/proto"
import fmt "fmt"

// Reference imports to suppress errors if they are not otherwise used.
var _ = fmt.Errorf

// WrinkledItem is used for items with multiple wrinkes
type WrinkledItem struct {
	// customer will contain the name of the customer
	Customer string
	// nested messages can be embedded directly using the tag compose:"embed"
	Item `compose:"embed"`
}

// SmoothItem is used as response with associated costs
type SmoothItem struct {
	Item `compose:"embed"`
	Cost int32 // cost in USD
}

// Item contains the information about a specific item
type Item struct {
	Name     string // db:"name" json:"name,omitempty"`
	Wrinkels int32  // db:"no_wrinkles" json:"wrinkels,omitempty"`
}

// --- STRUCT CONVERSION ---

// Convert will convert the proto struct to a custom type with
// tags and embedded structs if specified
func (from *WrinkledItem) Convert() (*protodef.WrinkledItem, error) {
	var err error

	if from == nil {
		return nil, nil
	}

	to := protodef.WrinkledItem{}

	to.Customer = from.Customer

	to.Item, err = from.Item.Convert()
	if err != nil {
		return nil, err
	}

	return &to, err
}

// Convert will convert the proto struct to a custom type with
// tags and embedded structs if specified
func (from *SmoothItem) Convert() (*protodef.SmoothItem, error) {
	var err error

	if from == nil {
		return nil, nil
	}

	to := protodef.SmoothItem{}

	to.Item, err = from.Item.Convert()
	if err != nil {
		return nil, err
	}

	to.Cost = from.Cost

	return &to, err
}

// Convert will convert the proto struct to a custom type with
// tags and embedded structs if specified
func (from *Item) Convert() (*protodef.Item, error) {
	var err error

	if from == nil {
		return nil, nil
	}

	to := protodef.Item{}

	to.Name = from.Name

	to.Wrinkels = from.Wrinkels

	return &to, err
}

// ConvertWrinkledItem will convert the proto optimized struct into
// an easier to use go structs
func ConvertWrinkledItem(from *protodef.WrinkledItem) (*WrinkledItem, error) {
	var err error

	if from == nil {
		return nil, nil
	}

	to := WrinkledItem{}

	to.Customer = from.GetCustomer()

	tmp, err := ConvertItem(from.GetItem())
	if err != nil {
		return nil, err
	}
	to.Item = *tmp

	return &to, err
}

// ConvertSmoothItem will convert the proto optimized struct into
// an easier to use go structs
func ConvertSmoothItem(from *protodef.SmoothItem) (*SmoothItem, error) {
	var err error

	if from == nil {
		return nil, nil
	}

	to := SmoothItem{}

	tmp, err := ConvertItem(from.GetItem())
	if err != nil {
		return nil, err
	}
	to.Item = *tmp

	to.Cost = from.GetCost()

	return &to, err
}

// ConvertItem will convert the proto optimized struct into
// an easier to use go structs
func ConvertItem(from *protodef.Item) (*Item, error) {
	var err error

	if from == nil {
		return nil, nil
	}

	to := Item{}

	to.Name = from.GetName()

	to.Wrinkels = from.GetWrinkels()

	return &to, err
}
