// Code generated by protoc-gen-gotags. DO NOT EDIT.
// source: startrek.proto

/*
Package startrek is a generated protocol buffer package.

It is generated from these files:
	startrek.proto

It has these top-level messages:
	StarfleetShip
*/
package startrek

import fmt "fmt"
import dkfbasel_protobuf "github.com/dkfbasel/protobuf/types/timestamp"
import dkfbasel_protobuf1 "github.com/dkfbasel/protobuf/types/nullstring"
import dkfbasel_protobuf2 "github.com/dkfbasel/protobuf/types/nullint"

// Reference imports to suppress errors if they are not otherwise used.
var _ = fmt.Errorf

// StarfleetShip ...
type StarfleetShipAlias struct {
	Name          string                        // db:"name"
	Passengers    *dkfbasel_protobuf2.NullInt    // db:"passengers"
	Operation     *dkfbasel_protobuf1.NullString // db:"operation"
	DepartureTime *dkfbasel_protobuf.Timestamp  // db:"departure_time_of_ship"
}
