// Code generated by protoc-gen-go. DO NOT EDIT.
// source: grpcservice.proto

/*
Package grpcservice is a generated protocol buffer package.

It is generated from these files:
	grpcservice.proto

It has these top-level messages:
	WrinkledItem
	SmoothItem
	Item
*/
package grpcservice

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import dkfbasel_protobuf "github.com/dkfbasel/protobuf/types/timestamp"
import dkfbasel_protobuf1 "github.com/dkfbasel/protobuf/types/nullstring"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// WrinkledItem is used for items with multiple wrinkes
type WrinkledItem struct {
	// customer will contain the name of the customer
	Customer string `protobuf:"bytes,1,opt,name=customer" json:"customer,omitempty"`
	// nested messages can be embedded directly using the tag compose:"embed"
	Item               *Item                          `protobuf:"bytes,4,opt,name=item" json:"item,omitempty"`
	BroughtIn          *dkfbasel_protobuf.Timestamp   `protobuf:"bytes,5,opt,name=brought_in,json=broughtIn" json:"brought_in,omitempty"`
	ThisCouldBeNothing *dkfbasel_protobuf1.NullString `protobuf:"bytes,6,opt,name=this_could_be_nothing,json=thisCouldBeNothing" json:"this_could_be_nothing,omitempty"`
}

func (m *WrinkledItem) Reset()                    { *m = WrinkledItem{} }
func (m *WrinkledItem) String() string            { return proto.CompactTextString(m) }
func (*WrinkledItem) ProtoMessage()               {}
func (*WrinkledItem) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *WrinkledItem) GetCustomer() string {
	if m != nil {
		return m.Customer
	}
	return ""
}

func (m *WrinkledItem) GetItem() *Item {
	if m != nil {
		return m.Item
	}
	return nil
}

func (m *WrinkledItem) GetBroughtIn() *dkfbasel_protobuf.Timestamp {
	if m != nil {
		return m.BroughtIn
	}
	return nil
}

func (m *WrinkledItem) GetThisCouldBeNothing() *dkfbasel_protobuf1.NullString {
	if m != nil {
		return m.ThisCouldBeNothing
	}
	return nil
}

// SmoothItem is used as response with associated costs
type SmoothItem struct {
	Item *Item `protobuf:"bytes,1,opt,name=item" json:"item,omitempty"`
	Cost int32 `protobuf:"varint,2,opt,name=cost" json:"cost,omitempty"`
}

func (m *SmoothItem) Reset()                    { *m = SmoothItem{} }
func (m *SmoothItem) String() string            { return proto.CompactTextString(m) }
func (*SmoothItem) ProtoMessage()               {}
func (*SmoothItem) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *SmoothItem) GetItem() *Item {
	if m != nil {
		return m.Item
	}
	return nil
}

func (m *SmoothItem) GetCost() int32 {
	if m != nil {
		return m.Cost
	}
	return 0
}

// Item contains the information about a specific item
type Item struct {
	Name     string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Wrinkels int32  `protobuf:"varint,2,opt,name=wrinkels" json:"wrinkels,omitempty"`
}

func (m *Item) Reset()                    { *m = Item{} }
func (m *Item) String() string            { return proto.CompactTextString(m) }
func (*Item) ProtoMessage()               {}
func (*Item) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Item) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Item) GetWrinkels() int32 {
	if m != nil {
		return m.Wrinkels
	}
	return 0
}

func init() {
	proto.RegisterType((*WrinkledItem)(nil), "grpcservice.WrinkledItem")
	proto.RegisterType((*SmoothItem)(nil), "grpcservice.SmoothItem")
	proto.RegisterType((*Item)(nil), "grpcservice.Item")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Butler service

type ButlerClient interface {
	// Iron will take a wrinkled item and remove all wrinkels
	Iron(ctx context.Context, in *WrinkledItem, opts ...grpc.CallOption) (*SmoothItem, error)
}

type butlerClient struct {
	cc *grpc.ClientConn
}

func NewButlerClient(cc *grpc.ClientConn) ButlerClient {
	return &butlerClient{cc}
}

func (c *butlerClient) Iron(ctx context.Context, in *WrinkledItem, opts ...grpc.CallOption) (*SmoothItem, error) {
	out := new(SmoothItem)
	err := grpc.Invoke(ctx, "/grpcservice.Butler/Iron", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Butler service

type ButlerServer interface {
	// Iron will take a wrinkled item and remove all wrinkels
	Iron(context.Context, *WrinkledItem) (*SmoothItem, error)
}

func RegisterButlerServer(s *grpc.Server, srv ButlerServer) {
	s.RegisterService(&_Butler_serviceDesc, srv)
}

func _Butler_Iron_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WrinkledItem)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ButlerServer).Iron(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpcservice.Butler/Iron",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ButlerServer).Iron(ctx, req.(*WrinkledItem))
	}
	return interceptor(ctx, in, info, handler)
}

var _Butler_serviceDesc = grpc.ServiceDesc{
	ServiceName: "grpcservice.Butler",
	HandlerType: (*ButlerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Iron",
			Handler:    _Butler_Iron_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "grpcservice.proto",
}

func init() { proto.RegisterFile("grpcservice.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 321 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x50, 0x4f, 0x4b, 0xfb, 0x40,
	0x14, 0xfc, 0xe5, 0x47, 0x5a, 0xec, 0xd6, 0x4b, 0x17, 0xc4, 0x18, 0x14, 0x6a, 0x40, 0xe8, 0x29,
	0x85, 0x0a, 0x5e, 0xf4, 0x54, 0x41, 0xc9, 0xa5, 0x48, 0x2a, 0x78, 0x0c, 0x4d, 0xfa, 0x9a, 0x2c,
	0xdd, 0x3f, 0x65, 0xf7, 0xad, 0x7e, 0x5d, 0x3f, 0x8a, 0x64, 0x9b, 0xd4, 0x14, 0xc5, 0xdb, 0x7b,
	0x3b, 0x33, 0x6f, 0x67, 0x86, 0x8c, 0x4a, 0xbd, 0x2b, 0x0c, 0xe8, 0x77, 0x56, 0x40, 0xbc, 0xd3,
	0x0a, 0x15, 0x1d, 0x76, 0x9e, 0xc2, 0xeb, 0xf5, 0x76, 0x93, 0xaf, 0x0c, 0xf0, 0xa9, 0x03, 0x73,
	0xbb, 0x99, 0x22, 0x13, 0x60, 0x70, 0x25, 0x76, 0x7b, 0x7e, 0x18, 0xfd, 0xa4, 0x48, 0xcb, 0xb9,
	0x41, 0xcd, 0x64, 0xb9, 0xe7, 0x44, 0x9f, 0x1e, 0x39, 0x7d, 0xd3, 0x4c, 0x6e, 0x39, 0xac, 0x13,
	0x04, 0x41, 0x43, 0x72, 0x52, 0x58, 0x83, 0x4a, 0x80, 0x0e, 0xbc, 0xb1, 0x37, 0x19, 0xa4, 0x87,
	0x9d, 0xde, 0x10, 0x9f, 0x21, 0x88, 0xc0, 0x1f, 0x7b, 0x93, 0xe1, 0x6c, 0x14, 0x77, 0x2d, 0xd6,
	0xe2, 0xd4, 0xc1, 0xf4, 0x9e, 0x90, 0x5c, 0x2b, 0x5b, 0x56, 0x98, 0x31, 0x19, 0xf4, 0x1c, 0xf9,
	0x32, 0x6e, 0xcd, 0xc4, 0xad, 0x99, 0xf8, 0xb5, 0xf5, 0x9b, 0x0e, 0x1a, 0x7e, 0x22, 0xe9, 0x0b,
	0x39, 0xc3, 0x8a, 0x99, 0xac, 0x50, 0x96, 0xaf, 0xb3, 0x1c, 0x32, 0xa9, 0xb0, 0x62, 0xb2, 0x0c,
	0xfa, 0xee, 0xce, 0xd5, 0x2f, 0x77, 0x16, 0x96, 0xf3, 0xa5, 0x0b, 0x95, 0xd2, 0x5a, 0xfb, 0x58,
	0x4b, 0xe7, 0xb0, 0xd8, 0x0b, 0xa3, 0x67, 0x42, 0x96, 0x42, 0x29, 0xac, 0x5c, 0xbe, 0x36, 0x83,
	0xf7, 0x77, 0x06, 0x4a, 0xfc, 0x42, 0x19, 0x0c, 0xfe, 0x8f, 0xbd, 0x49, 0x2f, 0x75, 0x73, 0x74,
	0x47, 0xfc, 0xa4, 0xc1, 0xe4, 0x4a, 0x40, 0x53, 0x8f, 0x9b, 0xeb, 0xda, 0x3e, 0xea, 0x1a, 0x81,
	0x9b, 0x46, 0x73, 0xd8, 0x67, 0x4f, 0xa4, 0x3f, 0xb7, 0xc8, 0x41, 0xd3, 0x07, 0xe2, 0x27, 0x5a,
	0x49, 0x7a, 0x71, 0xf4, 0x6d, 0xb7, 0xff, 0xf0, 0xfc, 0x08, 0xfa, 0x36, 0x1e, 0xfd, 0xcb, 0xfb,
	0x2e, 0xf1, 0xed, 0x57, 0x00, 0x00, 0x00, 0xff, 0xff, 0x20, 0x80, 0x87, 0x74, 0x1b, 0x02, 0x00,
	0x00,
}
